[project]
name = "01-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chanchal2003", email = "85550866+chanchal2003@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
01-setup = "01_setup:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
